#title: Мой блог
description: Это мой блог, созданный с помощью GitHub Pages.
baseurl: ""
Ъbaseurl: "/victenna.github.io" # имя вашего репозитория
url: "https://victenna.github.io" # ваш GitHub username

# Настройки темы
#theme: minima
#theme: jekyll-theme-minimal

# Пользовательские настройки
author:
  name: Victor
  email: vrabinov@gmail.com
