# Site settings
title: My Personal Blog       # Name of your site
email: vrabinov@gmail.com      # Your email address
description: >                # Description of your site for SEO
  This is my personal blog where I write about tech, life, and more.
baseurl: ""                   # Base URL for your project
url: "victenna.github.io"     # Your site URL
twitter_username: johndoe     # Your Twitter handle
github_username: victenna     # Your GitHub username

# Build settings
theme: minima                 # Theme name, e.g., "minima", "jekyll-theme-cayman", etc.
markdown: kramdown            # Markdown engine
permalink: /:categories/:title/  # Permalink structure
paginate: 5                   # Posts per page on pagination
plugins:                      # List of plugins
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

